---
- block:
    - name: Check PostgreSQL master database exists
      stat: path={{ postgresql_data_dir }}/PG_VERSION
      register: postgresql_master_db_st

    - name: Initialize PostgreSQL master database
      command: "{{ postgresql_bin_dir }}/postgresql{{ postgresql_major_minor_version }}-setup initdb"
      environment:
        PGSETUP_INITDB_OPTIONS: '-E utf8 --no-locale'
      when: not postgresql_master_db_st.stat.exists

    - name: Update postgresql pg_hba.conf at master
      template: src=pg_hba.conf.j2 dest={{ postgresql_data_dir }}/pg_hba.conf owner=postgres group=postgres mode=0644

    - name: Update postgresql.conf master
      blockinfile:
        dest: "{{ postgresql_data_dir }}/postgresql.conf"
        backup: true
        mode: 0600
        state: present
        block: |
          # my customized options
          listen_addresses = '*'
          port = {{ postgresql_port }}
          logging_collector = on
          archive_mode = on
          archive_command = 'cp %p {{ postgresql_archive_dir }}/%f'
          hot_standby = on
          hot_standby_feedback = on
          max_replication_slots = 8
          max_standby_streaming_delay = -1
          max_standby_archive_delay = -1
          max_wal_senders = 8
          restart_after_crash = off
          synchronous_commit = on
          wal_keep_segments = 1000
          wal_level = hot_standby
          wal_receiver_status_interval = 2

          # pgpool-II config
          pgpool.pg_ctl = '{{ postgresql_bin_dir }}/pg_ctl'
      # NOTE: Use become_user here so that backup file is created with that user
      become: true
      become_user: postgres

    # NOTE: Do not enable postgresql service since they are started by pgpool-II
    - name: Start master PostgreSQL just to create {{ postgresql_replication_user }} user
      service: name=postgresql-{{ postgresql_major_dot_minor_version }} state=started enabled=false
      when: not postgresql_master_db_st.stat.exists

    - name: Create insert_lock table in PostgreSQL template1 database for pgpool-II
      command: "{{ postgresql_bin_dir }}/psql -f {{ postgresql_prefix_dir }}/share/pgpool-II/insert_lock.sql template1"
      become: true
      become_user: postgres
      when: not postgresql_master_db_st.stat.exists

    - name: Install pgpool_recovery extention in PostgreSQL template1 database for pgpool-II
      command: "{{ postgresql_bin_dir }}/psql -f {{ postgresql_prefix_dir }}/share/extension/pgpool-recovery.sql template1"
      become: true
      become_user: postgres
      when: not postgresql_master_db_st.stat.exists

    - name: Create PostgreSQL user for replication
      postgresql_user: name={{ postgresql_replication_user }} password={{ postgresql_replication_password }} role_attr_flags=LOGIN,REPLICATION state=present
      become: true
      become_user: postgres
      when: not postgresql_master_db_st.stat.exists
  run_once: true
  delegate_to: "{{ postgresql_master_nodename }}"

- name: Check if node is PostgreSQL standby
  set_fact:
    postgresql_is_standby_node: "{{ inventory_hostname_short != postgresql_master_nodename }}"

- block:
    - name: Check PostgreSQL standby database exists
      stat: path={{ postgresql_data_dir }}/PG_VERSION
      register: postgresql_standby_db_st

    - name: Create PostgreSQL standby database
      command: "{{ postgresql_bin_dir }}/pg_basebackup -h {{ postgresql_peer_ipaddr }} -p {{ postgresql_port }} -U {{ postgresql_replication_user }} -D {{ postgresql_data_dir }} --xlog --checkpoint=fast"
      become: true
      become_user: postgres
      when: not postgresql_standby_db_st.stat.exists
  when: "{{ postgresql_is_standby_node }}"

- name: Start and enable PostgreSQL service
  service: name=postgresql-{{ postgresql_major_dot_minor_version }} state=stopped enabled=false

- name: Start and enable pgpool-II service
  service: name=pgpool-II-{{ postgresql_major_minor_version }} state=stopped enabled=false
