---
- name: Install base packages
  yum: name={{ item }} state=present
  with_items:
    - sudo
    - vim-enhanced
    - less
    - tar
    - bind-utils
    - nmap-ncat
    - man
    - file
    - which
    # NOTE: PostgreSQL YUM depends on EPEL repository
    # http://yum.postgresql.org/repopackages.php
    - epel-release
